version: '3'
services:
  watermill:
    image: golang:1.12
    command: /bin/true
    volumes:
      - .:/app
      - .mod-cache:/go/pkg/mod
    working_dir: /app

    environment:
      WATERMILL_TEST_NATS_URL: nats://nats-streaming:4222


