version: '3'
services:
  watermill:
    image: golang:1.12
    command: /bin/true
    volumes:
      - .:/app
      - .mod-cache:/go/pkg/mod
    working_dir: /app

    environment:
      WATERMILL_TEST_AMQP_URI: amqp://guest:guest@rabbitmq:5672


